id: I0BF6BC1C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T08:02:57+00:00'
last_modified: '2022-06-08T18:07:03.561241+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1GS105195
  title: ཐོབ་ཡིག་བུམ་པ་བཟང་པོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E9AE:
      image_group_id: I1PD36271
      title: Volume 1 of thob yig bum pa bzang po
      total_pages: 216
      order: 1
      base_file: E9AE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
