id: P008056
initial_creation_type: ocr
source_metadata:
  id: bdr:W1GS105195
  title: ཐོབ་ཡིག་བུམ་པ་བཟང་པོ
  author: ''
  volumes:
    11f4427581294e59bb592fbac54026fe:
      image_group_id: I1PD36271
      title: ''
      volume_number: 1
      total_pages: 216
ebook_metadata:
  title: ཐོབ་ཡིག་བུམ་པ་བཟང་པོ
  author: ''
  sku: P008056
  cover: cover.jpg
  layers:
  - pagination
