id: P008056
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1GS105195
  title: ཐོབ་ཡིག་བུམ་པ་བཟང་པོ
  author: ''
  volumes:
    ad0f94acf89942beb0fa5f0f7b4ee91d:
      image_group_id: I1PD36271
      title: Volume 1 of thob yig bum pa bzang po
      volume_number: 1
      total_pages: 216
      base_file: v001.txt
